/* models/builder.ts */

/* Imports */
import { Prisma } from "@prisma/client";

import SchemaBuilder from "@pothos/core";
import ErrorsPlugin from "@pothos/plugin-errors";
import PrismaPlugin from "@pothos/plugin-prisma";
import PrismaTypes from "@pothos/plugin-prisma/generated";
import { DateResolver } from "graphql-scalars";

import { prisma } from "@models/db";
import { IContext } from "@utils/context";

/* Create Pothos schema builder */
export const builder = new SchemaBuilder<{
  /* Set default nullability & requiredness */
  DefaultFieldNullability: true;
  DefaultInputFieldRequiredness: true;
  /* Define context shape */
  Context: IContext;
  /* Define custom scalars */
  Scalars: {
    Date: { Input: Date; Output: Date };
  };
  /* Provide types generated by Prisma */
  PrismaTypes: PrismaTypes;
}>({
  /* Set default nullability & requiredness */
  defaultFieldNullability: true,
  defaultInputFieldRequiredness: true,
  /* Load plugins */
  /* Errors plugin must come before the validation plugin */
  plugins: [ErrorsPlugin, PrismaPlugin],
  /* Set error options */
  errorOptions: {
    defaultTypes: [],
  },
  /* Set Prisma options */
  prisma: {
    client: prisma,
    dmmf: Prisma.dmmf,
    filterConnectionTotalCount: true,
  },
});

/* Add custom scalars */
builder.addScalarType("Date", DateResolver, {});
